#!/usr/bin/env bash
# This script transfers a file from the client to a server using scp.

if [ "$#" -lt 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path=$1
server_ip=$2
username=$3
ssh_key=$4

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip":~/ || { echo "Error transferring file"; exit 1; }

echo "File transferred successfully to $username@$server_ip:~/"

