#!/usr/bin/env bash
# This script installs and configures Nginx on the server
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx start
