#!/usr/bin/env bash
# gives information about the school file
# if file exist print "school file exists"

if [ -e school ]
  then
    echo "school file exists"
    if [ -s school ]
      then
        echo "school file is not empty"
    else
      echo "school file is empty"
    fi
    if [ -f school ]
      then
        echo "school is a regular file"
    fi
else
  echo "school file does not exists"
fi
