#!/usr/bin/env bash
# Backup /etc/hosts file

sudo cp /etc/hosts /etc/hosts.bak

sudo sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /etc/hosts
sudo sed -i 's/^[0-9.]*[[:space:]]*facebook.com/8.8.8.8\tfacebook.com/' /etc/hosts

echo "IP addresses updated successfully."
