#!/usr/bin/env bash
# Install nginx if not already installed
if ! command -v nginx &> /dev/null; then
    apt-get update
    apt-get install -y nginx
fi
service nginx stop
sed -i 's/user\s*root;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/listen\s*80;/listen *:8080;/' /etc/nginx/sites-available/default
service nginx start
